services:
  - type: web
    name: freeflow-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn freeflow.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: freeflow-db
          property: connectionString

databases:
  - name: freeflow-db
    region: oregon
    plan: free
